## create user ##
POST http://localhost:8000/register HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=a&password=ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb
